---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: ''
  label: Content
  create: all
  match: "*.md"
  exclude: README.md
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
  instant_preview_command: npm run forestry:preview
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
